{
 "title": "TeaStore Logs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Service", "label": "Service", "query": "label_values(filename)" }
  ]
 },
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=~\".*${Service}.*\"}"
    }
   ]
  }
 ]
}
{
 "title": "TeaStore Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_utilization_ratio, k8s_namespace_name)"
   },
   {
    "name": "Container",
    "label": "Container",
    "query": "label_values(container_cpu_utilization_ratio{k8s_namespace_name=\"$Namespace\"}, k8s_container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Consumption (Utilization Ratio)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{k8s_namespace_name=\"$Namespace\", k8s_container_name=~\"^.*${Container}.*$|${Container}\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{k8s_namespace_name=\"$Namespace\", k8s_container_name=~\"^.*${Container}.*$|${Container}\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Cluster Node Health (Memory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "k8s_node_memory_usage_bytes", "legendFormat": "{{k8s_node_name}} Used" },
    {
     "expr": "k8s_node_memory_available_bytes",
     "legendFormat": "{{k8s_node_name}} Available"
    }
   ]
  }
 ]
}